/**
 * generatePDF.js — AXIOM Styled PDF Report Generator
 *
 * Produces a dark-theme A4 PDF that mirrors the AXIOM UI:
 *   - Dark background (#07070b)
 *   - Purple->teal gradient colour scheme (solid approximations)
 *   - All sections: Header, Assumptions, Agent Debates, Alternative Worlds, Footer
 */
import { jsPDF } from 'jspdf'

// ── Palette ──────────────────────────────────────────────────────────────────
const C = {
  bg:          [7,   7,  11],
  purpleDark:  [124,  58, 237],
  purple:      [167, 139, 250],
  teal:        [ 56, 189, 248],
  white:       [255, 255, 255],
  lightGray:   [226, 232, 240],
  smoke:       [100, 116, 139],
  divider:     [ 30,  20,  50],
  red:         [239,  68,  68],
  yellow:      [234, 179,   8],
  green:       [ 34, 197,  94],
  pink:        [232, 121, 249],
  historian:   [167, 139, 250],
  contrarian:  [239,  68,  68],
  scientist:   [ 56, 189, 248],
  philosopher: [ 34, 197,  94],
  investor:    [251, 191,  36],
  corporate_critic: [239, 68, 68],
  target_customer:  [56, 189, 248],
  growth_hacker:    [34, 197, 94],
}

function scoreColor(score) {
  if (score > 70) return C.red
  if (score > 45) return C.yellow
  return C.green
}

function riskColor(risk) {
  const map = { catastrophic: C.red, high: C.red, medium: C.yellow, low: C.green }
  return map[risk] || C.purple
}

function agentColor(agentKey) {
  return C[agentKey] || C.purple
}

const PAGE_W    = 210
const PAGE_H    = 297
const MARGIN    = 14
const CONTENT_W = PAGE_W - MARGIN * 2

export function generateAxiomPDF(results, field) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  let y = MARGIN
  let pageNum = 1

  function fillBackground() {
    doc.setFillColor(...C.bg)
    doc.rect(0, 0, PAGE_W, PAGE_H, 'F')
  }

  function drawFooter() {
    const footerY = PAGE_H - 7
    doc.setFontSize(6.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(60, 60, 80)
    doc.text('Generated by AXIOM · axiom.ai', MARGIN, footerY)
    const pl = `Page ${pageNum}`
    doc.text(pl, PAGE_W - MARGIN - doc.getTextWidth(pl), footerY)
    doc.setDrawColor(40, 30, 60)
    doc.setLineWidth(0.2)
    doc.line(MARGIN, footerY - 3, PAGE_W - MARGIN, footerY - 3)
  }

  function addPage() {
    doc.addPage()
    pageNum++
    fillBackground()
    y = MARGIN
    drawFooter()
  }

  function ensureSpace(needed) {
    if (y + needed > PAGE_H - MARGIN - 10) addPage()
  }

  function drawDivider() {
    doc.setDrawColor(...C.divider)
    doc.setLineWidth(0.25)
    doc.line(MARGIN, y, PAGE_W - MARGIN, y)
    y += 4
  }

  function drawPurpleDivider() {
    doc.setDrawColor(139, 92, 246)
    doc.setLineWidth(0.4)
    doc.line(MARGIN, y, PAGE_W - MARGIN, y)
    y += 5
  }

  function drawSectionHeader(text, color) {
    ensureSpace(12)
    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...color)
    doc.text(text.toUpperCase(), MARGIN, y)
    y += 2
    doc.setDrawColor(...color)
    doc.setLineWidth(0.2)
    doc.line(MARGIN, y, PAGE_W - MARGIN, y)
    y += 5
  }

  function drawScoreBadge(score, cx, cy) {
    const col = scoreColor(score)
    doc.setFillColor(col[0] * 0.2, col[1] * 0.2, col[2] * 0.2)
    doc.setDrawColor(...col)
    doc.setLineWidth(0.4)
    doc.circle(cx, cy, 5, 'FD')
    doc.setFontSize(7)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...col)
    const lbl = String(score)
    doc.text(lbl, cx - doc.getTextWidth(lbl) / 2, cy + 2.5)
  }

  function drawRiskBadge(risk, x, bY) {
    const col = riskColor(risk)
    const lbl = (risk || 'unknown').toUpperCase()
    doc.setFontSize(6)
    doc.setFont('helvetica', 'bold')
    const tw = doc.getTextWidth(lbl)
    doc.setFillColor(col[0] * 0.15, col[1] * 0.15, col[2] * 0.15)
    doc.setDrawColor(...col)
    doc.setLineWidth(0.3)
    doc.roundedRect(x, bY - 3, tw + 3, 4.5, 1.5, 1.5, 'FD')
    doc.setTextColor(...col)
    doc.text(lbl, x + 1.5, bY)
  }

  // ─ Build document ──────────────────────────────────────────────────────────
  fillBackground()
  drawFooter()

  // ── HEADER ────────────────────────────────────────────────────────────────
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.purple)
  doc.text('AXIOM BLIND SPOT REPORT', MARGIN, y)
  y += 7

  const fieldDisplay = '"' + ((field || '').charAt(0).toUpperCase()) + ((field || '').slice(1)) + '"'
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.white)
  const fLines = doc.splitTextToSize(fieldDisplay, CONTENT_W - 24)
  doc.text(fLines, MARGIN, y)
  y += fLines.length * 8.5

  const score   = results.overall_blind_spot_score ?? 0
  const sCol    = scoreColor(score)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...sCol)
  doc.text('Overall Blind Spot Score: ' + score + '/100', MARGIN, y)
  y += 5.5

  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.smoke)
  doc.text(
    (results.total_assumptions ?? 0) + ' assumptions detected   |   ' +
    (results.critical_count ?? 0) + ' critical',
    MARGIN, y
  )
  y += 6

  drawPurpleDivider()

  // ── ASSUMPTIONS ───────────────────────────────────────────────────────────
  drawSectionHeader('Layer 1 — Assumptions Detected', C.purple)

  ;(results.results || []).forEach((r, i) => {
    const assumption = r.assumption || {}
    const bss        = r.blind_spot_score || {}
    const aText      = assumption.assumption || ''
    const whyHidden  = assumption.why_hidden || ''
    const aScore     = bss.score ?? 0
    const aRisk      = bss.risk_level || 'unknown'
    const evidence   = assumption.evidence_strength || ''
    const col        = scoreColor(aScore)

    // Estimate card height
    doc.setFontSize(9)
    const tLines = doc.splitTextToSize(aText, CONTENT_W - 20)
    doc.setFontSize(7.5)
    const wLines = whyHidden ? doc.splitTextToSize(whyHidden, CONTENT_W - 20) : []
    const cardH  = 5 + tLines.length * 3.8 + 6 + (whyHidden ? 4 + wLines.length * 3.1 : 0) + 5
    ensureSpace(cardH + 2)

    // Card bg
    doc.setFillColor(col[0] * 0.06, col[1] * 0.06, col[2] * 0.06)
    doc.setDrawColor(col[0] * 0.4, col[1] * 0.4, col[2] * 0.4)
    doc.setLineWidth(0.25)
    doc.roundedRect(MARGIN, y, CONTENT_W, cardH, 3, 3, 'FD')

    // Number circle
    const bcx = MARGIN + 6.5
    const bcy = y + 6
    doc.setFillColor(...C.purpleDark)
    doc.circle(bcx, bcy, 4.5, 'F')
    doc.setFontSize(7)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...C.white)
    const n = String(i + 1)
    doc.text(n, bcx - doc.getTextWidth(n) / 2, bcy + 2.5)

    // Score badge (right)
    drawScoreBadge(aScore, PAGE_W - MARGIN - 7, bcy)

    // Assumption text
    let itemY = y + 3
    const tx  = MARGIN + 14
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...C.white)
    doc.text(tLines, tx, itemY)
    itemY += tLines.length * 3.8 + 2

    // Risk + evidence
    drawRiskBadge(aRisk, tx, itemY)
    doc.setFontSize(6)
    const rw = doc.getTextWidth((aRisk || '').toUpperCase()) + 5
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...C.smoke)
    doc.text(evidence + ' evidence', tx + rw + 2, itemY)
    itemY += 5

    // Why hidden
    if (whyHidden) {
      doc.setFontSize(7)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...C.purple)
      doc.text('Why Hidden:', tx, itemY)
      itemY += 3.5
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...C.lightGray)
      doc.text(wLines, tx, itemY)
      itemY += wLines.length * 3.1
    }

    y = Math.max(y + cardH, itemY) + 4
  })

  y += 3

  // ── AGENT DEBATES ─────────────────────────────────────────────────────────
  ensureSpace(16)
  drawSectionHeader('Agent Debates', C.teal)

  const SKIP = ['synthesis']
  ;(results.results || []).forEach((r, i) => {
    const assumption = r.assumption || {}
    const debate     = r.debate || {}
    const bss        = r.blind_spot_score || {}
    const aText      = assumption.assumption || ''
    const aScore     = bss.score ?? 0

    ensureSpace(20)

    doc.setFontSize(8.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...C.white)
    const assLines = doc.splitTextToSize((i + 1) + '. ' + aText, CONTENT_W)
    doc.text(assLines, MARGIN, y)
    y += assLines.length * 3.5 + 2

    const sCol2 = scoreColor(aScore)
    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...sCol2)
    doc.text('Blind Spot Score: ' + aScore + '/100', MARGIN, y)
    y += 4

    Object.keys(debate).filter(k => !SKIP.includes(k)).forEach(key => {
      const data      = debate[key] || {}
      const challenge = data.challenge || data.perspective || data.weakest_point || data.hidden_premise || ''
      const agCol     = agentColor(key)
      const label     = key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())

      doc.setFontSize(7.5)
      const chLines = doc.splitTextToSize(challenge, CONTENT_W - 16)
      ensureSpace(6 + chLines.length * 3.2)

      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...agCol)
      doc.text('> ' + label, MARGIN + 2, y)
      y += 3.8

      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...C.lightGray)
      doc.text(chLines, MARGIN + 6, y)
      y += chLines.length * 3.2 + 2
    })

    const synthesis = debate.synthesis || {}
    if (synthesis.strongest_challenge) {
      const sLines = doc.splitTextToSize(synthesis.strongest_challenge, CONTENT_W - 10)
      ensureSpace(8 + sLines.length * 3)
      doc.setFontSize(7)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...C.purple)
      doc.text('Synthesis:', MARGIN + 2, y)
      y += 3.5
      doc.setFont('helvetica', 'italic')
      doc.setTextColor(...C.lightGray)
      doc.text(sLines, MARGIN + 6, y)
      y += sLines.length * 3 + 2
    }

    y += 2
    drawDivider()
  })

  // ── ALTERNATIVE WORLDS ────────────────────────────────────────────────────
  ensureSpace(16)
  drawSectionHeader('Alternative Worlds', C.pink)

  const allWorlds = (results.results || [])
    .flatMap(r => (r.alternative_worlds || []).map(w => ({
      ...w,
      parent_assumption: r.assumption?.assumption || '',
      parent_score: r.blind_spot_score?.score ?? 0,
    })))
    .sort((a, b) => b.parent_score - a.parent_score)
    .slice(0, 9)

  if (!allWorlds.length) {
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.setTextColor(...C.smoke)
    doc.text('No alternative worlds generated.', MARGIN, y)
    y += 6
  } else {
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.setTextColor(...C.lightGray)
    const intro = 'What reality could look like if these assumptions are wrong — ordered by impact.'
    const introLines = doc.splitTextToSize(intro, CONTENT_W)
    doc.text(introLines, MARGIN, y)
    y += introLines.length * 3.5 + 4

    allWorlds.forEach((world, i) => {
      const worldName = world.world_name || ('Alternative World ' + (i + 1))
      const desc      = world.description || ''
      const opp       = world.startup_opportunity || ''

      doc.setFontSize(8)
      const dLines = doc.splitTextToSize(desc, CONTENT_W - 10)
      doc.setFontSize(7.5)
      const oLines = opp ? doc.splitTextToSize(opp, CONTENT_W - 10) : []
      const blockH = 7 + 4 + dLines.length * 3.2 + (opp ? 3 + oLines.length * 3 : 0) + 5
      ensureSpace(blockH)

      // Circle badge
      const bcx = MARGIN + 4
      const bcy = y + 4
      doc.setFillColor(...C.purpleDark)
      doc.circle(bcx, bcy, 3, 'F')
      doc.setFontSize(6)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...C.white)
      const n2 = String(i + 1)
      doc.text(n2, bcx - doc.getTextWidth(n2) / 2, bcy + 2)

      // World name
      doc.setFontSize(10)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...C.white)
      const wnLines = doc.splitTextToSize(worldName, CONTENT_W - 10)
      doc.text(wnLines, MARGIN + 9, y + 1.5)
      y += wnLines.length * 4 + 2

      // Description
      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...C.lightGray)
      doc.text(dLines, MARGIN + 4, y)
      y += dLines.length * 3.2 + 2

      // Startup opportunity
      if (opp) {
        doc.setFontSize(7)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(...C.purple)
        doc.text('Startup Opportunity:', MARGIN + 4, y)
        y += 3.5
        doc.setFont('helvetica', 'italic')
        doc.text(oLines, MARGIN + 8, y)
        y += oLines.length * 3 + 2
      }

      y += 3
      if (i < allWorlds.length - 1) drawDivider()
    })
  }

  // ── SAVE ──────────────────────────────────────────────────────────────────
  const date     = new Date().toISOString().split('T')[0]
  const safeName = (field || 'report').replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '')
  doc.save('AXIOM_Report_' + safeName + '_' + date + '.pdf')
}
